###
POST http://localhost:8000/user/
accept: application/json
Content-Type: application/json

{
  "name": "Felipe Melo",
  "email": "mf@flu.com",
  "dept": "Security",
  "password": "1231111",
  "currency": "USD"
}

###

